// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package reusable

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Checkbox() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<button class=\"checkbox-button\" style=\"height:100%;width:100%;background-color: transparent;border:none;margin:1rem 0.75rem 1rem 0.5rem;\"><svg viewBox=\"0 0 36 36\" height=\"100%\" width=\"100%\" style=\"stroke-width:5;stroke-linecap:square;\"><!-- X-mark --><path d=\"M0 0 L36 36 M36 0 L0 36 M0 0\" stroke=\"red\" fill=\"none\"><animate id=\"x-animation\" begin=\"indefinite\" fill=\"freeze\" attributeName=\"d\" dur=\"500ms\" to=\"M0 0 L36 36 M36 0 L0 36 M0 0\"></animate> <animate id=\"red-animation\" begin=\"indefinite\" fill=\"freeze\" attributeName=\"stroke\" dur=\"500ms\" to=\"red\"></animate><!-- Checkmark --><animate id=\"check-animation\" begin=\"indefinite\" fill=\"freeze\" attributeName=\"d\" dur=\"500ms\" to=\"M0 22 L20 36 L33.5 0 M0 18\"></animate> <animate id=\"green-animation\" begin=\"indefinite\" fill=\"freeze\" attributeName=\"stroke\" dur=\"500ms\" to=\"green\"></animate></path></svg></button><script>\n    function handleClick(e) {\n      if (e.currentTarget.classList.contains('check')) {\n        document.getElementById('x-animation').beginElement();\n        document.getElementById('red-animation').beginElement();\n        e.currentTarget.classList.remove('check');\n      } else {\n        document.getElementById('check-animation').beginElement();\n        document.getElementById('green-animation').beginElement();\n        e.currentTarget.classList.add('check');\n      }\n    }\n    for (const button of document.getElementsByClassName('checkbox-button')) {\n      button.addEventListener('click', handleClick);\n    }\n  </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
