// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package reusable

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// 3 SVG circles that grow and shrink on endless repeat (general design by Sam Herbert)
// The SMIL animation has the 2 outer circles shrinking to start, while the inner grows
// They also follow a similar pattern with their opacity, dimming, brightening and dimming, respectively.
func LoadingCircles() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<svg width=\"120\" height=\"30\" viewBox=\"0 0 120 30\" fill=\"#ffffff\"><circle cx=\"15\" cy=\"15\" r=\"15\"><animate attributeName=\"r\" dur=\"1s\" values=\"15;6;15\" repeatCount=\"indefinite\"></animate> <animate attributeName=\"fill-opacity\" dur=\"1s\" values=\"1; 0.5; 1\" repeatCount=\"indefinite\"></animate></circle> <circle cx=\"60\" cy=\"15\" r=\"6\" fill-opacity=\"0.5\"><animate attributeName=\"r\" dur=\"1s\" values=\"6;15;6\" repeatCount=\"indefinite\"></animate> <animate attributeName=\"fill-opacity\" dur=\"1s\" values=\"0.5; 1; 0.5\" repeatCount=\"indefinite\"></animate></circle> <circle cx=\"105\" cy=\"15\" r=\"15\"><animate attributeName=\"r\" dur=\"1s\" values=\"15;6;15\" repeatCount=\"indefinite\"></animate> <animate attributeName=\"fill-opacity\" dur=\"1s\" values=\"1; 0.5; 1\" repeatCount=\"indefinite\"></animate></circle></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
