name: Run Golang Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  go_tests:
    name: Go Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['1.23', '1.24']

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go get ./...
      - name: Build project
        run: go build -v ./...
      - name: Test via Go CLI
        run: go test -v
        env:
          IS_CI: "true"
          EXPECTED_ROOT: "/GOTH-BFF/GOTH-BFF"
